services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    env_file:
      - .env.prod 
  
  django-web:
    build: .
    container_name: django-docker
    ports: 
      - "8000:8080"
    depends_on:
      - db 
    volumes:
      - ./static:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env.prod

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro 
      - ./media:/media
    depends_on:
      - django-web

volumes:
  postgres_data:
